include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Scaffold has intentional TODO(johar) extension points.
    todo: ignore

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: false
